language: node_js
node_js:
  - "8"
deploy:
  provider: heroku
  app: desear
  api_key:
    secure: cqheBLZ4ItFPUdHD+YxOSQja6G0rGCu0ZjX+yaSAmhvns57MKupyMpH8DL3Ya+88AY8ULLAU2ujg2uEUDilnAU494Qx/cWCbmHRcVoHoDSvfuSnUJyiqSLg5ep4EfQPqUrwyTJuarVpFDosI5jwjfLkaVvEEudRZb5f6Bs+8ZbtM8AnoZ+FLwND2ab8u58bker+1ILuPr7QYAB1jYTWHJUxV6BDpZOtjgXVFrswthsJ602DjWS7ALgeBdpZHGq8RW80jE4ptwjkqGrdVIPze7FlYO+cllaHvdARoGJMHr7JmW2FnR/aIbL39RajOBKyBAYGEwfjMi1AHZDh4jtoUyeQjT8/tX8xAfbI2tt9GWZCx84L9WweqL5hZn3/E+mdYTEmfgwtOdhUx/bljri/snM8aPmtMFR1nOvoh7/5yc0D0Xl5v7iT019X/ol6tlCrve4/lMZYJt2euXi03rODsBv0Ty6HkM4vZNjF31Mc793dehLxxAzgNrZoaf4UT/vVWgEX/C3M7lqCenQjYnuiV+FIyL1G+IH9BxV+ENrd/jcv5pIRDAxR7L8tWU97tqHX395fgki6OCwy3PUM68fFVQbzi7ujxSXDol8KeKh47oqTcsYu8A74cMtbtOhD+WKBQBqqKX7kbsud203D6oes9E9vNLR5VFHGe4KYWDsQBxPk=
